#!/bin/bash
#apt-get install xdg-utils
TARGET="$1"
BROWSER="xdg-open"
VER="1.9"
OKBLUE='\033[94m'
OKRED='\033[91m'
OKGREEN='\033[92m'
OKORANGE='\033[93m'
DELAY=1
RESET='\e[0m'

# LOAD WEBSITE IN A WEB BROSER
$BROWSER "https://www.giftofspeed.com/cache-checker/" 2> /dev/null
